### ISSUE TITLE
Update code to support Bootstrap 3

### ISSUE THREAD

**Issue by erobit** [erobit/meteor-accounts-ui-bootstrap-dropdown#19]
The latest bootstrap IMHO is a huge leap forward. With mobile first design, reduction in code size and a rewrite of most of their javascript modules, I'm looking forward to moving to support it in the near future.

**Comment by mrmowgli** [comment]
+1  Using the atmosphere package bootstrap3-less completely breaks all of the meteor-accounts-ui-bootstrap-dropdown functionality.  None of the dropdowns work.  I'd love to be able to switch!

**Comment by dkvdm** [comment]
I forked and created a basic hacky version here: https://github.com/flxfxp/meteor-accounts-ui-bootstrap-dropdown
However, I did translate it to Dutch in the process, sorry about that.
Looks fine with Bootstrap 3, insert inside nav <ul>, no <li> tags needed.

``` css
    .login-dropdown {
        width: 360px;
        padding: 20px;
        padding-bottom: 20px;
        .alert{
            padding: 7px;
            margin-bottom: 10px !important;
        }
        div.login-button{
            .border-radius();
            padding: 10px;
            color: @btn-primary-color;
            i{
                margin-right: 10px;
            }
        }
        div.login-button:hover, a#forgot-password-link:hover{
            cursor: pointer;
        }
        #login-buttons-facebook{
            margin-bottom: 4px;
            background-color: #3b5998;
        }
        #login-buttons-facebook:hover{
            background-color: lighten(#3b5998, 20%);
        }
        #login-buttons-google{
            margin-bottom: 4px;
            background-color: #dd4b39;
        }
        #login-buttons-google:hover{
            background-color: lighten(#dd4b39, 20%);
        }
        #login-buttons-twitter{
            margin-bottom: 14px;
            background-color: #00acee;
        }
        #login-buttons-twitter:hover{
            background-color: lighten(#00acee, 20%);
        }
    }


.accounts-centered-dialog{
    margin-top: 30px;
    position: fixed;
    z-index: 2040;
    right: auto;
    left: 50%;
    width: 600px;
    padding: 10px 10px 15px;
    margin-left: -250px;
    background-color: #fff;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 6px;
    outline: medium none;
    -webkit-box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.5);
    background-clip: padding-box;
    .modal-instructions{
        margin-top: 10px;
    }
    .form-group{
        input{
            width: 300px;
        }
    }
}
```
